#By Oran Zhang
ass = <<EOF
[Script Info]
; Script generated by Aegisub 3.2.2
; http://www.aegisub.org/
Title: Default Aegisub file
ScriptType: v4.00+
WrapStyle: 0
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601
PlayResX: 640
PlayResY: 360

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Hiragino Sans GB,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,1:33:36.62,1:33:38.82,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:38.82,1:33:41.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:41.70,1:33:42.66,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:42.66,1:33:44.74,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:45.14,1:33:47.46,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:47.46,1:33:50.26,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:50.26,1:33:53.34,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:53.34,1:33:54.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:55.06,1:33:57.26,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:57.26,1:33:59.66,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:33:59.66,1:34:01.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:01.86,1:34:04.34,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:04.38,1:34:06.34,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:06.34,1:34:08.38,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:08.38,1:34:10.14,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:10.14,1:34:11.78,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:11.78,1:34:13.50,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:13.50,1:34:15.26,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:15.26,1:34:16.50,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:17.06,1:34:20.14,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:20.14,1:34:21.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:21.86,1:34:24.58,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:24.58,1:34:26.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:26.70,1:34:28.34,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:28.86,1:34:31.34,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:31.34,1:34:33.38,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:33.38,1:34:34.50,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:35.02,1:34:36.14,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:36.14,1:34:37.22,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:40.58,1:34:41.06,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:41.06,1:34:43.58,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:43.58,1:34:45.50,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:45.50,1:34:46.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:46.70,1:34:48.46,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:48.46,1:34:50.54,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:50.54,1:34:52.14,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:34:52.14,1:34:53.38,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:02.54,1:35:03.82,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:03.82,1:35:06.22,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:06.22,1:35:07.38,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:07.38,1:35:09.82,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:09.82,1:35:10.66,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:13.98,1:35:16.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:16.62,1:35:17.90,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:17.90,1:35:19.06,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:19.06,1:35:19.82,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:19.82,1:35:20.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:20.86,1:35:21.58,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:21.58,1:35:22.34,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:22.34,1:35:23.30,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:32.50,1:35:35.94,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:35.94,1:35:37.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:37.62,1:35:39.38,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:39.38,1:35:39.94,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:39.94,1:35:41.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:41.70,1:35:43.74,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:43.74,1:35:46.58,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:46.58,1:35:48.06,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:48.06,1:35:49.54,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:49.54,1:35:51.50,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:51.50,1:35:52.54,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:52.54,1:35:54.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:54.86,1:35:56.22,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:56.22,1:35:57.94,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:57.94,1:35:59.10,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:35:59.10,1:36:02.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:02.86,1:36:05.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:05.62,1:36:07.10,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:07.10,1:36:08.46,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:08.46,1:36:09.78,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:09.78,1:36:11.82,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:11.82,1:36:13.58,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:13.58,1:36:14.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:14.86,1:36:16.22,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:16.22,1:36:17.06,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:17.06,1:36:18.46,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:18.46,1:36:19.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:19.70,1:36:21.94,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:21.94,1:36:24.38,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:24.38,1:36:26.42,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:26.42,1:36:29.10,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:29.10,1:36:31.82,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:31.82,1:36:33.26,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:33.26,1:36:34.02,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:34.02,1:36:36.54,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:36.54,1:36:38.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:38.62,1:36:40.74,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:40.74,1:36:42.74,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:50.38,1:36:52.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:52.70,1:36:54.42,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:54.42,1:36:55.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:55.86,1:36:58.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:36:58.62,1:37:01.22,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:01.22,1:37:03.26,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:06.10,1:37:07.90,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:07.90,1:37:09.06,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:09.06,1:37:10.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:10.70,1:37:12.30,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:12.30,1:37:15.06,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:15.06,1:37:17.42,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:17.42,1:37:19.86,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:19.86,1:37:22.66,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:22.66,1:37:24.62,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:24.62,1:37:26.18,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:26.18,1:37:26.98,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:26.98,1:37:28.78,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:28.78,1:37:30.90,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:30.90,1:37:34.02,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:34.02,1:37:34.70,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
Dialogue: 0,1:37:34.70,1:37:37.18,Default,,0,0,0,,复活节克拉克和郭富城尽快了解或过分
EOF

text = <<EOF
If you're going less than 5km
please take public transportation, ride a bike, or carpool
If you drive a car
Don't let the engine idle longer than 30 seconds
If you see a diesel vehicle belching black exhaust
Try calling 12369 to report it
Those “black tails” behind diesel trucks are full of PM2.5
they endanger public health.
If you see a restaurant releasing cooking smoke
Ask them to install a filtering system
Or leave them a negative review online
If you see dust blowing from uncovered piles at construction sites
If you think there might be a leak at a gas station
Try calling 12369
If you burn coal at home
As much as you can, try to avoid low-quality coal
As much as you can, try to avoid low-quality coal
Ask your mom to clean the kitchen range and hood
to keep the family healthy
And you can try taking pictures to help locate industrial pollution sources
supervise and report illegal activity
and tweet @ your local environmental bureau on Weibo
Check out the list of polluting manufacturers
and boycott their products
When our air quality laws are being written and revised
participate in the public commenting process
and make your voice heard
With  a little thought and care,
the smog will start to clear
Before,
When I walked by the uncovered construction site near my home
I usually just covered my nose and went on past
But now I know
At lease 15% of Beijing's PM2.5 pollution
At lease 15% of Beijing's PM2.5 pollution
comes from blowing dust
I decided I had to try
(Chai) We live nearby
(Chai) Why haven't you covered this dirt?
(Worker) Ask our boss
(Chai) Okay, where's your boss?
(Worker) Over there, go look over there
(Chai) You haven’t covered that huge dirt pile alongside the road
(Chai) As soon as the wind blows, the dust flies everywhere
(Boss) I know, I know, I know, I know
(Boss) It’s our fault
(Chai) So when are you going to cover it?
(Boss) Right away
(Chai) Okay
(Workers) Sorry, sorry.
The whole process took less than five minutes
Right before I left
The worker who told me where to find the boss
said, 
“Do you know why he's afraid of you?”
He pointed at the mobile phone in my hand
He's afraid you'll expose him
In my building there is a restaurant downstairs
It serves meat pies
And every mealtime
Everywhere in the building
smells like smoke
Before, I didn’t think this is was a problem
Isn't every Chinese restaurant in the world like this?
But now I know
Beijing's food service industry creates
at least 6% of our PM2.5 pollution
And Beijing is home to
12% of the country's food service industry
For such a high-volume restaurant,
I used to think there was nothing to be done about it
until I went to London
and had a meal in a Chinese restaurant there.
I discovered there was no smoke smell there at all
Why?
The boss took me 
up to the roof
And I saw this
which is called a soot purifier
The London city government required them to install it
And the city inspects it regularly
I thought it must be pretty high-tech
until I came back to Beijing
I found that not only does Beijing have them too
installing them is actually required
I called 12369 to make a report
And a week later
this item was delivered:
It all took less than half an hour
When I was taking this video clip
The restaurant boss came over
and said, “Thank you for your supervision as a resident here
We hope to see you in our restaurant in the future”
For the past year, our office lunches have been nothing but meat pies. 
Sometimes when I walk by the neighborhood gas station
(here's a gas station downstairs)
I can smell the very strong scent of gasoline
I can smell the very strong scent of gasoline
But I thought that all gas stations worldwide are like this
until I went to the United States
I saw this thing on their gas pump nozzles
it's called “gasoline vapor recovery equipment”
I thought it was another high-tech thing
until I came back to Beijing and discovered
We've had these things for ages
and they've been required since 2008
but many people don't maintain them properly
so they release a lot of gasoline vapor
Then
I called 12369 again
1
2
3
4
5
6
7
8
EOF

regexp = /Dialogue: 0,.*,Default,,0,0,0,,(.*)/
original_ass = {context: ass, start_line: 17}
text_array = text.split "\n"
ass_a_o = (original_ass[:context].split "\n")
ass_array = []
ass_a_o[(original_ass[:start_line])..(ass_a_o.count-1)].each_index do |i|
  before_r = regexp.match(ass_a_o[original_ass[:start_line]+ i])[1]
  ass_array << ass_a_o[ original_ass[:start_line] + i ].gsub(before_r, text_array[i])
end
ret = (ass_a_o[0..(original_ass[:start_line]-1)].join "\n") + "\n" + (ass_array.join "\n")

f = File.new "./out.ass", "w+"
f.puts ret
f.close

